SUBDIRS = curl_request_maker twitter_api script_detector sentiment_analyser keywords_extracter trends_manager follow_analyser

.PHONY: subdirs $(SUBDIRS)

subdirs: $(SUBDIRS)

$(SUBDIRS):
	$(MAKE) -C $@

clean:
	@ for dir in $(SUBDIRS); do \
	    cd $$dir; make clean; cd ..; \
	  done
